services:
  zerotier-monitor:
    build: .
    container_name: zerotier-monitor
    user: "1000:1000"
    env_file: .env
    environment:
      - SSH_CONFIG_FILE=/home/sherlockes/.ssh/config
      - HOME=/home/sherlockes
      - TZ=Europe/Madrid
    volumes:
      - ./data:/app/data
      - ~/.ssh:/home/sherlockes/.ssh
      - ~/.ssh/config:/home/sherlockes/.ssh/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # Quitamos "ports" para que no sea accesible públicamente por el puerto 8081
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
